// URLS
export const COSTUMERS = "https://localhost:7062/api/Costumers/"
export const APPOINTMENT = "https://localhost:7062/api/Appointments"
export const SERVICE = "https://localhost:7062/api/Services/"
export const LOGIN = "https://localhost:7062/api/Auth/Login"
export const TOKEN_VALIDATION = "https://localhost:7062/api/Auth/validate?token="
export const REGISTRATION = "https://localhost:7062/api/Auth/Register/"
export const STATISTICS = "https://localhost:7062/api/Statistics/"
export const FILES_JSON = "assets/files.json"
export const SERVICES_JSON = "assets/services.json"
export const MASTERS = "https://localhost:7062/api/Master/"
export const SCHEDULES = "https://localhost:7062/api/MasterSchedules"
export const COUNTRIES_JSON = "../assets/countries.json"
export const DAYS_JSON = "../assets/dataDaysOfWeek"
export const IN_PROGRESS = "Выполняется"
export const COMPLETED = "Готово"
export const REJECTED = "Отменено"
export const MISSED = "Клиент не пришел"
export const BUTTON_ITEMS = "assets/buttonChoise.json"
export const WARNING = "var(--red-600)"
export const SUCCESS = "var(--green-600)"
export const CURRENT = "var(--orange-600)"
export const OLD = "var(--surface-600)"
